<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIemelsy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIemelsy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIemelsy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIemelsy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIemelsy\appProdProjectContainer([
    'container.build_hash' => 'Iemelsy',
    'container.build_id' => '3bb7dc16',
    'container.build_time' => 1574689373,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIemelsy');
