<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCppvjh5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCppvjh5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCppvjh5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCppvjh5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCppvjh5\appDevDebugProjectContainer([
    'container.build_hash' => 'Cppvjh5',
    'container.build_id' => '44be03c1',
    'container.build_time' => 1574689455,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCppvjh5');
